Update to version 2.1.1
- Speed up argument parsing
- Include more information in execution error message
- Bugfix: Prevent redo from quitting with non-zero exit status on success
- Bugfix: Allow invoking redo with '/'
- Bugfix: Allow directories starting with '-'
- Bugfix: Parse options --mindepth= and --maxdepth= correctly

diff --git a/redo b/redo
--- a/redo
+++ b/redo
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-version="2.1"
+version="2.1.1"
 
 set -eu
 shopt -s nullglob
@@ -15,7 +15,7 @@ function traverse {
 	for d in "$@"; do
 		((DEPTH)) || ((RINDEX++))
 		((INDEX++))
-		d="${d%/}"
+		[[ $d != '/' ]] && d="${d%/}"
 		if ! [[ -d $d ]]; then
 			$quiet || echo "redo: ${CWD:+$CWD/}$d: no such directory" >&2
 			continue
@@ -25,7 +25,7 @@ function traverse {
 			$quiet || echo "redo: ${CWD:+$CWD/}$d: permission denied" >&2
 			continue
 		fi
-		$nocwd || cd "./$d"
+		$nocwd || cd -- "$d"
 		((DEPTH++))
 		((RUNS++))
 
@@ -51,21 +51,17 @@ function traverse {
 		fi
 		count=${#dirs[@]}
 		for e in . .. ${exclude[@]+${exclude[@]}}; do
-			i=0
-			while ((i < count)); do
+			for ((i = 0; i < count; i++)); do
 				[[ ${dirs[i]%/} == ${e%/} ]] && unset 'dirs[i]'
-				((i++))
 			done
 		done
 
 		if [[ -z ${mindepth-} || $DEPTH -ge $mindepth ]]; then
 			DIR="$d"
-			if ! $nocwd; then
-				[[ $d == '.' ]] && CWD='.' || CWD="${PWD#*$ROOT/}"
-			fi
+			$nocwd || CWD="${PWD#$ROOT/}"
 			eval "$cmd" ${argv[@]+"${argv[@]}"} && err=0 || err=$?
 			if ((err)); then
-				$quiet || echo "redo: ${c:-$exe}: error $err" >&2
+				$quiet || echo "redo: ${CWD:-$DIR}: $cmd: error $err" >&2
 				$strict && exit $err
 			fi
 		fi
@@ -74,11 +70,12 @@ function traverse {
 		((DEPTH--))
 		$nocwd || cd ..
 	done
+	return 0
 }
 
 function cleanup {
 	rm -f "$script"
-	exit
+	exit 0
 }
 
 if [[ ${1-} == '--help' ]]; then
@@ -103,6 +100,7 @@ exdir=()
 dirs=()
 argv=()
 cmd=''
+set=''
 nocwd=false
 strict=false
 quiet=false
@@ -110,52 +108,75 @@ follow=false
 opt=true
 glob=true
 file=true
-export DIR=. CWD=. COUNT=0 RCOUNT=0 INDEX=0 RINDEX=0 DEPTH=0 RUNS=0 ROOT="$PWD"
+export DIR='' CWD='' COUNT=0 RCOUNT=0 INDEX=0 RINDEX=0 DEPTH=0 RUNS=0 ROOT="$PWD"
 
 for arg in "$@"; do
-	if [[ -n ${set-} ]]; then
+	if [[ -n $set ]]; then
 		declare $set="$arg"
 		set=''
-	else
-		if $opt && [[ $arg == '--' ]]; then
+		continue
+	fi
+	if $opt; then
+		if [[ $arg == '--' ]]; then
 			opt=false
-		elif $opt && [[ $arg == '--nocwd' || $arg == '--nocd' ]]; then
+			continue
+		elif [[ $arg == '--nocwd' || $arg == '--nocd' ]]; then
 			nocwd=true
-		elif $opt && [[ $arg == '--follow' ]]; then
+			continue
+		elif [[ $arg == '--follow' ]]; then
 			follow=true
-		elif $opt && [[ $arg == '--depth' ]]; then
+			continue
+		elif [[ $arg == '--depth' ]]; then
 			set=depth
-		elif $opt && [[ $arg == --depth=* ]]; then
+			continue
+		elif [[ $arg == --depth=* ]]; then
 			depth="${arg:8}"
-		elif $opt && [[ $arg == '--mindepth' ]]; then
+			continue
+		elif [[ $arg == '--mindepth' ]]; then
 			set=mindepth
-		elif $opt && [[ $arg == --mindepth=* ]]; then
-			mindepth="${arg:8}"
-		elif $opt && [[ $arg == '--maxdepth' ]]; then
+			continue
+		elif [[ $arg == --mindepth=* ]]; then
+			mindepth="${arg:11}"
+			continue
+		elif [[ $arg == '--maxdepth' ]]; then
 			set=maxdepth
-		elif $opt && [[ $arg == --maxdepth=* ]]; then
-			maxdepth="${arg:8}"
-		elif $opt && [[ $arg == '--strict' ]]; then
+			continue
+		elif [[ $arg == --maxdepth=* ]]; then
+			maxdepth="${arg:11}"
+			continue
+		elif [[ $arg == '--strict' ]]; then
 			strict=true
-		elif $opt && [[ $arg == '--quiet' ]]; then
+			continue
+		elif [[ $arg == '--quiet' ]]; then
 			quiet=true
-		elif $opt && [[ ${arg:0:2} == '--' ]]; then
+			continue
+		elif [[ ${arg:0:2} == '--' ]]; then
 			echo "redo: unrecognized option '${arg:2}'" >&2
 			exit 2
-		elif $glob && [[ $arg == '+' ]]; then
+		fi
+	fi
+	if $glob; then
+		if [[ $arg == '+' ]]; then
 			glob=false
 			opt=false
-		elif $file && [[ $arg == '-' ]]; then
+			continue
+		elif [[ ${arg:0:1} == '-' ]]; then
+			[[ $arg == */ ]] || arg+=/
+			exdir+=("${arg:1}")
+			continue
+		elif [[ ${arg:0:1} == '+' ]]; then
+			[[ $arg == */ ]] || arg+=/
+			indir+=("${arg:1}")
+			continue
+		fi
+	fi
+	if $file; then
+		if [[ $arg == '-' ]]; then
 			glob=false
 			opt=false
 			file=false
-		elif $glob && [[ ${arg:0:1} == '-' ]]; then
-			[[ $arg == */ ]] || arg+=/
-			exdir+=("${arg:1}")
-		elif $glob && [[ ${arg:0:1} == '+' ]]; then
-			[[ $arg == */ ]] || arg+=/
-			indir+=("${arg:1}")
-		elif $file && [[ -d $arg ]]; then
+			continue
+		elif [[ -d $arg ]]; then
 			if ! $follow && [[ -L $arg ]]; then
 				$quiet || echo "redo: $arg: symlink not followed" >&2
 			else
@@ -163,9 +184,10 @@ for arg in "$@"; do
 			fi
 			glob=false
 			opt=false
-		elif $file && [[ -f $arg ]]; then
+			continue
+		elif [[ -f $arg ]]; then
 			if [[ -x $arg ]]; then
-				cmd="\"$(realpath "$arg")\""
+				cmd="\"$(realpath -- "$arg")\""
 			else
 				read -r line < "$arg"
 				if [[ ${line:0:2} == '#!' ]]; then
@@ -173,23 +195,25 @@ for arg in "$@"; do
 				else
 					cmd="$SHELL"
 				fi
-				argv=("\"$(realpath "$arg")\"")
+				argv=("\"$(realpath -- "$arg")\"")
 			fi
 			glob=false
 			opt=false
 			file=false
-		elif [[ -z $cmd ]]; then
-			cmd="$arg"
-			glob=false
-			opt=false
-			file=false
-		else
-			argv+=("$arg")
+			continue
 		fi
+	fi
+	if [[ -z $cmd ]]; then
+		cmd="$arg"
+		glob=false
+		opt=false
+		file=false
+	else
+		argv+=("$arg")
 	fi
 done
 
-if [[ -n ${set-} ]]; then
+if [[ -n $set ]]; then
 	echo "redo: option '$set' requires an argument" >&2
 	exit 2
 fi
@@ -212,15 +236,13 @@ if ! ((${#dirs[@]})); then
 	fi
 	count=${#dirs[@]}
 	for e in . .. ${exdir[@]+${exdir[@]}}; do
-		i=0
-		while ((i < count)); do
+		for ((i = 0; i < count; i++)); do
 			[[ ${dirs[i]%/} == ${e%/} ]] && unset 'dirs[i]'
-			((i++))
 		done
 	done
 fi
 
-((${#dirs[@]})) || exit
+((${#dirs[@]})) || exit 0
 
 if [[ -n $cmd ]]; then
 	traverse "${dirs[@]}"
@@ -235,7 +257,7 @@ else
 		printf "%s\n" "$line" > "$script"
 	fi
 	cat >> "$script"
-	argv=("$script")
+	argv=("\"$script\"")
 	traverse "${dirs[@]}"
 	cleanup
 fi
