Update to version 2.1
Accept variable number of program arguments on the command line

diff --git a/redo b/redo
--- a/redo
+++ b/redo
@@ -1,12 +1,12 @@
 #!/bin/bash
 
-version="2.0"
+version="2.1"
 
 set -eu
 shopt -s nullglob
 IFS=$'\t\n'
 
-function recurse {
+function traverse {
 	INDEX=0
 	COUNT=$#
 	((DEPTH)) || RCOUNT=$#
@@ -63,23 +63,14 @@ function recurse {
 			if ! $nocwd; then
 				[[ $d == '.' ]] && CWD='.' || CWD="${PWD#*$ROOT/}"
 			fi
-			err=0
-			exe=''
-			for c in "${cmd[@]}"; do
-				if [[ -z $exe ]]; then
-					exe="$c"
-				else
-					$exe ${c:+"$c"} ${var+"${!var}"} || err=$?
-					if ((err)); then
-						$quiet || echo "redo: ${c:-$exe}: error $err" >&2
-						$strict && exit $err
-					fi
-					exe=''
-				fi
-			done
+			eval "$cmd" ${argv[@]+"${argv[@]}"} && err=0 || err=$?
+			if ((err)); then
+				$quiet || echo "redo: ${c:-$exe}: error $err" >&2
+				$strict && exit $err
+			fi
 		fi
 
-		((${#dirs[@]})) && recurse "${dirs[@]}"
+		((${#dirs[@]})) && traverse "${dirs[@]}"
 		((DEPTH--))
 		$nocwd || cd ..
 	done
@@ -92,10 +83,10 @@ function cleanup {
 
 if [[ ${1-} == '--help' ]]; then
 	cat <<-'EOF'
-		usage: redo [--quiet] [--strict] [--follow] [--nocd] [--arg VAR]
-		            [--depth N] [--mindepth N] [--maxdepth N]
+		usage: redo [--quiet] [--strict] [--follow] [--nocd]
+		            [--mindepth N] [--maxdepth N] [--depth N]
 		            [--] [+INCLUDE_GLOB ...] [-EXCLUDE_GLOB ...]
-		            [DIR ...] [SCRIPT_OR_EXECUTABLE ...]
+		            [+] [DIR ...] [-] [SCRIPT_OR_EXECUTABLE [ARG ...]]
 		variables: DIR, CWD, COUNT, INDEX, DEPTH, RUNS
 		           ROOT, RCOUNT, RINDEX
 	EOF
@@ -110,13 +101,15 @@ fi
 indir=()
 exdir=()
 dirs=()
-cmd=()
+argv=()
+cmd=''
 nocwd=false
 strict=false
 quiet=false
 follow=false
 opt=true
 glob=true
+file=true
 export DIR=. CWD=. COUNT=0 RCOUNT=0 INDEX=0 RINDEX=0 DEPTH=0 RUNS=0 ROOT="$PWD"
 
 for arg in "$@"; do
@@ -128,10 +121,6 @@ for arg in "$@"; do
 			opt=false
 		elif $opt && [[ $arg == '--nocwd' || $arg == '--nocd' ]]; then
 			nocwd=true
-		elif $opt && [[ $arg == '--arg' ]]; then
-			set=var
-		elif $opt && [[ $arg == --arg=* ]]; then
-			var="${arg:6}"
 		elif $opt && [[ $arg == '--follow' ]]; then
 			follow=true
 		elif $opt && [[ $arg == '--depth' ]]; then
@@ -153,30 +142,20 @@ for arg in "$@"; do
 		elif $opt && [[ ${arg:0:2} == '--' ]]; then
 			echo "redo: unrecognized option '${arg:2}'" >&2
 			exit 2
-		elif [[ $arg == '-' || $arg == '+' ]]; then
+		elif $glob && [[ $arg == '+' ]]; then
 			glob=false
 			opt=false
+		elif $file && [[ $arg == '-' ]]; then
+			glob=false
+			opt=false
+			file=false
 		elif $glob && [[ ${arg:0:1} == '-' ]]; then
 			[[ $arg == */ ]] || arg+=/
 			exdir+=("${arg:1}")
 		elif $glob && [[ ${arg:0:1} == '+' ]]; then
 			[[ $arg == */ ]] || arg+=/
 			indir+=("${arg:1}")
-		elif [[ -f $arg ]]; then
-			if [[ -x $arg ]]; then
-				cmd+=("$(realpath "$arg")" "")
-			else
-				read -r line < "$arg"
-				if [[ ${line:0:2} == '#!' ]]; then
-					cmd+=("${line:2}")
-				else
-					cmd+=("$SHELL")
-				fi
-				cmd+=("$(realpath "$arg")")
-			fi
-			glob=false
-			opt=false
-		elif [[ -d $arg ]]; then
+		elif $file && [[ -d $arg ]]; then
 			if ! $follow && [[ -L $arg ]]; then
 				$quiet || echo "redo: $arg: symlink not followed" >&2
 			else
@@ -184,13 +163,28 @@ for arg in "$@"; do
 			fi
 			glob=false
 			opt=false
-		elif ! $strict; then
-			cmd+=("$arg" "")
+		elif $file && [[ -f $arg ]]; then
+			if [[ -x $arg ]]; then
+				cmd="\"$(realpath "$arg")\""
+			else
+				read -r line < "$arg"
+				if [[ ${line:0:2} == '#!' ]]; then
+					cmd="${line:2}"
+				else
+					cmd="$SHELL"
+				fi
+				argv=("\"$(realpath "$arg")\"")
+			fi
 			glob=false
 			opt=false
+			file=false
+		elif [[ -z $cmd ]]; then
+			cmd="$arg"
+			glob=false
+			opt=false
+			file=false
 		else
-			echo "redo: $arg: no such file or directory" >&2
-			exit 1
+			argv+=("$arg")
 		fi
 	fi
 done
@@ -198,15 +192,6 @@ done
 if [[ -n ${set-} ]]; then
 	echo "redo: option '$set' requires an argument" >&2
 	exit 2
-fi
-if [[ -n ${var+1} ]]; then
-	if [[ -z $var ]]; then
-		echo "redo: option 'arg' requires a variable name as argument" >&2
-		exit 2
-	elif [[ -z ${!var+1} ]]; then
-		echo "redo: undefined variable '$var'" >&2
-		exit 1
-	fi
 fi
 for opt in depth mindepth maxdepth; do
 	if [[ -n ${!opt+1} ]] && [[ -z ${!opt} || ${!opt} =~ [^0-9] ]]; then
@@ -237,20 +222,20 @@ fi
 
 ((${#dirs[@]})) || exit
 
-if ((${#cmd[@]})); then
-	recurse "${dirs[@]}"
+if [[ -n $cmd ]]; then
+	traverse "${dirs[@]}"
 else
 	script="$(mktemp -t redo)"
 	trap cleanup INT
 	read -r line
 	if [[ ${line:0:2} == '#!' ]]; then
-		cmd+=("${line:2}")
+		cmd="${line:2}"
 	else
-		cmd+=("$SHELL")
+		cmd="$SHELL"
 		printf "%s\n" "$line" > "$script"
 	fi
 	cat >> "$script"
-	cmd+=("$script")
-	recurse "${dirs[@]}"
+	argv=("$script")
+	traverse "${dirs[@]}"
 	cleanup
 fi
